"use client";

import { DashboardLayout } from "@/components/templates/DashboardLayout";
import { TokenColumn } from "@/components/organisms/TokenColumn";
import { TokenPopup } from "@/components/molecules/TokenPopup";
import type { Token } from "@/types";
import { useAppSelector } from "@/store/hooks";

// Sample token data matching the screenshot
const sampleTokens: Record<"new" | "final-stretch" | "migrated", Token[]> = {
  new: [
    {
      id: "1",
      name: "NYwhale New Year Whale",
      symbol: "NYwhale",
      address: "7Lbm...4U62",
      age: "2s",
      marketCap: 41700,
      volume: 10000,
      price: 0.001,
      priceChange24h: 0,
      holders: 8,
      transactions: 7,
      fee: 0.031,
      status: "new",
      metrics: {
        holdersPercent: 75,
        liquidityPercent: 75,
        timePercent: 75,
        targetPercent: 0,
        gearPercent: 0,
        holdersGearPercent: 0,
        liquidityTime: "14m",
      },
    },
    {
      id: "2",
      name: "$TRW The Russian Whale",
      symbol: "$TRW",
      address: "EoPq...pump",
      age: "4s",
      marketCap: 3940,
      volume: 112,
      price: 0.0001,
      priceChange24h: 0,
      holders: 2,
      transactions: 7,
      fee: 0.023,
      status: "new",
      metrics: {
        holdersPercent: 2,
        liquidityPercent: 2,
        timePercent: 2,
        targetPercent: 0,
        gearPercent: 0,
        holdersGearPercent: 0,
        liquidityTime: "53m",
      },
    },
    {
      id: "3",
      name: "Fish In a World Full Of Whales",
      symbol: "Fish",
      address: "3XBC...rFku",
      age: "6s",
      marketCap: 3450,
      volume: 123,
      price: 0.00005,
      priceChange24h: 0,
      holders: 3,
      transactions: 2,
      fee: 0.032,
      status: "new",
      metrics: {
        holdersPercent: 3,
        liquidityPercent: 3,
        timePercent: 3,
        targetPercent: 0,
        gearPercent: 0,
        holdersGearPercent: 0,
        liquidityTime: "12d",
      },
    },
    {
      id: "4",
      name: "McWhale The McDonald's Whale",
      symbol: "McWhale",
      address: "9Klm...xY12",
      age: "8s",
      marketCap: 7750,
      volume: 3000,
      price: 0.0002,
      priceChange24h: 0,
      holders: 24,
      transactions: 57,
      fee: 0.141,
      status: "new",
      metrics: {
        holdersPercent: 24,
        liquidityPercent: 2,
        timePercent: 5,
        targetPercent: 0,
        gearPercent: 28,
        holdersGearPercent: 0,
        liquidityTime: "4h",
      },
    },
    {
      id: "5",
      name: "Panda The Chinese Panda",
      symbol: "Panda",
      address: "2Pnd...a456",
      age: "10s",
      marketCap: 3460,
      volume: 200,
      price: 0.0001,
      priceChange24h: 0,
      holders: 5,
      transactions: 12,
      fee: 0.025,
      status: "new",
      metrics: {
        holdersPercent: 5,
        liquidityPercent: 5,
        timePercent: 5,
        targetPercent: 0,
        gearPercent: 0,
        holdersGearPercent: 0,
      },
    },
  ],
  "final-stretch": [
    {
      id: "6",
      name: "Tesla AI Tesla AI",
      symbol: "Tesla AI",
      address: "1Tsl...AI99",
      age: "40m",
      marketCap: 23300,
      volume: 8000,
      price: 0.002,
      priceChange24h: 0,
      holders: 32,
      transactions: 969,
      fee: 0.025,
      status: "final-stretch",
      metrics: {
        holdersPercent: 32,
        liquidityPercent: 0,
        timePercent: 25,
        targetPercent: 46,
        gearPercent: 49,
        holdersGearPercent: 0,
        liquidityTime: "40m",
      },
    },
    {
      id: "7",
      name: "Panda The Chinese Panda",
      symbol: "Panda",
      address: "2Pnd...a456",
      age: "26s",
      marketCap: 535000,
      volume: 15000,
      price: 0.01,
      priceChange24h: 0,
      holders: 19,
      transactions: 41,
      fee: 0.034,
      status: "final-stretch",
      metrics: {
        holdersPercent: 19,
        liquidityPercent: 0,
        timePercent: 19,
        targetPercent: 0,
        gearPercent: 0,
        holdersGearPercent: 0,
        liquidityTime: "12d",
      },
    },
    {
      id: "8",
      name: "PE PastirmaEgg",
      symbol: "PE",
      address: "4Egg...stir",
      age: "38s",
      marketCap: 513000,
      volume: 15000,
      price: 0.009,
      priceChange24h: 0,
      holders: 19,
      transactions: 43,
      fee: 0.033,
      status: "final-stretch",
      metrics: {
        holdersPercent: 19,
        liquidityPercent: 0,
        timePercent: 19,
        targetPercent: 0,
        gearPercent: 0,
        holdersGearPercent: 0,
        liquidityTime: "8d",
      },
    },
    {
      id: "9",
      name: "you you are the media now",
      symbol: "you",
      address: "5You...edia",
      age: "1m",
      marketCap: 28200,
      volume: 5000,
      price: 0.001,
      priceChange24h: 0,
      holders: 15,
      transactions: 35,
      fee: 0.028,
      status: "final-stretch",
      metrics: {
        holdersPercent: 15,
        liquidityPercent: 0,
        timePercent: 12,
        targetPercent: 0,
        gearPercent: 0,
        holdersGearPercent: 0,
      },
    },
  ],
  migrated: [
    {
      id: "10",
      name: "PG PayGate",
      symbol: "PG",
      address: "6Pay...Gate",
      age: "44s",
      marketCap: 43700,
      volume: 11000,
      price: 0.002,
      priceChange24h: 0,
      holders: 100,
      transactions: 22,
      fee: 0.033,
      status: "migrated",
      metrics: {
        holdersPercent: 100,
        liquidityPercent: 100,
        timePercent: 75,
        targetPercent: 0,
        gearPercent: 0,
        holdersGearPercent: 0,
        liquidityTime: "37m",
      },
    },
    {
      id: "11",
      name: "PG PayGate",
      symbol: "PG",
      address: "7Pay...Gate2",
      age: "1m",
      marketCap: 41800,
      volume: 56000,
      price: 0.002,
      priceChange24h: 0,
      holders: 28,
      transactions: 623,
      fee: 3.659,
      status: "migrated",
      metrics: {
        holdersPercent: 28,
        liquidityPercent: 2,
        timePercent: 6,
        targetPercent: 2,
        gearPercent: 6,
        holdersGearPercent: 0,
        liquidityTime: "56m",
      },
    },
    {
      id: "12",
      name: "Peanut Peanut",
      symbol: "Peanut",
      address: "8Pnt...anut",
      age: "1m",
      marketCap: 47500,
      volume: 12000,
      price: 0.002,
      priceChange24h: 0,
      holders: 2,
      transactions: 203,
      fee: 0.021,
      status: "migrated",
      metrics: {
        holdersPercent: 2,
        liquidityPercent: 0,
        timePercent: 8,
        targetPercent: 8,
        gearPercent: 0,
        holdersGearPercent: 0,
      },
    },
    {
      id: "13",
      name: "INNOCENT Pope Innocent XIV",
      symbol: "INNOCENT",
      address: "9Pop...cent",
      age: "1m",
      marketCap: 496000,
      volume: 15000,
      price: 0.01,
      priceChange24h: 0,
      holders: 100,
      transactions: 28,
      fee: 0.032,
      status: "migrated",
      metrics: {
        holdersPercent: 100,
        liquidityPercent: 19,
        timePercent: 18,
        targetPercent: 0,
        gearPercent: 0,
        holdersGearPercent: 0,
        liquidityTime: "27d",
      },
    },
    {
      id: "14",
      name: "RIAL Iranian Riallranian Rial",
      symbol: "RIAL",
      address: "0Ril...iran",
      age: "2m",
      marketCap: 71700,
      volume: 18000,
      price: 0.003,
      priceChange24h: 0,
      holders: 45,
      transactions: 67,
      fee: 0.035,
      status: "migrated",
      metrics: {
        holdersPercent: 45,
        liquidityPercent: 0,
        timePercent: 35,
        targetPercent: 0,
        gearPercent: 0,
        holdersGearPercent: 0,
      },
    },
  ],
};

export default function Home() {
  const selectedTokenId = useAppSelector((state) => state.ui.selectedTokenId);
  
  // Find the selected token from all token arrays
  const allTokens = [
    ...sampleTokens.new,
    ...sampleTokens["final-stretch"],
    ...sampleTokens.migrated,
  ];
  const selectedToken = allTokens.find((token) => token.id === selectedTokenId) || null;

  return (
    <DashboardLayout>
      <div className="w-full h-full flex flex-col overflow-hidden">
        <div className="grid grid-cols-1 md:grid-cols-3 gap-0 h-full min-h-0">
          {/* New Pairs Column */}
          <TokenColumn status="new" tokens={sampleTokens.new} />

          {/* Final Stretch Column */}
          <TokenColumn
            status="final-stretch"
            tokens={sampleTokens["final-stretch"]}
          />

          {/* Migrated Column */}
          <TokenColumn status="migrated" tokens={sampleTokens.migrated} />
        </div>
      </div>
      <TokenPopup token={selectedToken} />
    </DashboardLayout>
  );
}

